//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoCargas
    {
        public int id { get; set; }
        public Nullable<int> id_cargas { get; set; }
        public Nullable<int> id_lineaNegocio { get; set; }
    
        public virtual MenuCargas MenuCargas { get; set; }
    }
}
