//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int Id { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
        public Nullable<int> Id_Submenu { get; set; }
    
        public virtual LineaNegocio LineaNegocio { get; set; }
        public virtual Submenu Submenu { get; set; }
    }
}
