//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjusNcRealVsDevROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public Nullable<int> OPERADOR { get; set; }
        public string DEUDOR { get; set; }
        public Nullable<decimal> ProvisionTarifaMesAnterior { get; set; }
        public Nullable<decimal> ProvisionTarifaReal { get; set; }
        public Nullable<decimal> Ajustes_tarifa { get; set; }
    }
}
