//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionIngresoRom
    {
        public int Id { get; set; }
        public string Bandera { get; set; }
        public int No_Provision { get; set; }
        public int Id_Operador { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public int Id_Deudor { get; set; }
        public Nullable<decimal> Monto_Provision { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public System.DateTime Periodo { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> No_Documento { get; set; }
        public string Folio_Documento { get; set; }
        public decimal TC_Provision { get; set; }
        public decimal Importe_MXN { get; set; }
        public decimal Importe_Factura { get; set; }
        public decimal Div_Prov_Factura { get; set; }
        public decimal Tipo_Cambio_Factura { get; set; }
        public decimal Exceso_ProvMXN { get; set; }
        public decimal Insuficiencia_ProvMXN { get; set; }
        public int Activo { get; set; }
        public int Id_LineaNegocio { get; set; }
    }
}
