//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacProvTrafIngresoROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public Nullable<decimal> DevengoTrafico_MesCierre { get; set; }
        public Nullable<decimal> DevengoPendEmitir_FechaProvisionIngresoPendienteEmitir { get; set; }
        public Nullable<decimal> DevengoAcumulado_AFechaCierre { get; set; }
    }
}
