//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaDocumento
    {
        public int Id { get; set; }
        public string Id_Documento { get; set; }
        public string Periodo { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string EstatusCarga { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    }
}
