//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargaDocumentoRoaming
    {
        public int Id { get; set; }
        public string idDocumento { get; set; }
        public string periodoCarga { get; set; }
        public Nullable<System.DateTime> fechaCarga { get; set; }
        public string tipoCarga { get; set; }
        public string ordenCarga { get; set; }
        public string estatusCarga { get; set; }
    }
}
