//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int Id { get; set; }
        public Nullable<int> Operador_Id { get; set; }
        public Nullable<int> Trafico_Id { get; set; }
        public string TraficoDescripcion { get; set; }
        public string Concepto1 { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        public virtual Operador Operador { get; set; }
        public virtual Trafico Trafico { get; set; }
    }
}
