//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevAcumTraficoIngresoROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public Nullable<decimal> DevengoTrafico_MESCIERRE { get; set; }
        public Nullable<decimal> DevengoPendEmitirFechaProvisionIngresoPendienteEmitir { get; set; }
        public Nullable<decimal> DevengoAcumuladoFechaCierre { get; set; }
        public Nullable<decimal> DevengoAcumuladoA30_11_2018 { get; set; }
    }
}
