//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevengoAcumTraficoIng
    {
        public int Id { get; set; }
        public string PLMN { get; set; }
        public string Operador { get; set; }
        public string deudor { get; set; }
        public Nullable<decimal> devengoTrafico { get; set; }
        public Nullable<decimal> devengoPendEmitir { get; set; }
        public Nullable<decimal> devengoAcumulado { get; set; }
    }
}
