//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaTraficoROM
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> FECHATRAFICO { get; set; }
        public string PLMN { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public string OPERADOR { get; set; }
        public string FOLIOFACTURASAP { get; set; }
        public Nullable<decimal> REPORTEARMONTHLYINVOICE { get; set; }
        public Nullable<decimal> FACTURADOSINIMPUESTOS { get; set; }
        public Nullable<decimal> POREMITIR { get; set; }
        public string GRUPO { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> MXN { get; set; }
    }
}
