//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HPolizasRechazo
    {
        public long Id { get; set; }
        public string Poliza { get; set; }
        public string Sentido { get; set; }
        public string Estado { get; set; }
        public string Nombre { get; set; }
        public string PeriodoConsumido { get; set; }
        public string DescripcionMensaje { get; set; }
        public string Rechazado { get; set; }
        public string Reprocesado { get; set; }
        public Nullable<bool> PolizaGenerada { get; set; }
        public Nullable<System.DateTime> FechaHistorico { get; set; }
    }
}
