//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogActualizaciones
    {
        public int Id { get; set; }
        public string NombrePantalla { get; set; }
        public string ColumnaModificada { get; set; }
        public string Valor_Nuevo { get; set; }
        public string Valor_Anterior { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Direccion_IP { get; set; }
        public string Accion { get; set; }
        public string Usuario { get; set; }
        public int Activo { get; set; }
    }
}
