//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Id { get; set; }
        public string Direccion { get; set; }
        public int Id_Operador { get; set; }
        public int Id_Servicio { get; set; }
        public string Tipo_Movimiento { get; set; }
        public int Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        public virtual Operador Operador { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
