//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrosCargaDocumento
    {
        public int Id { get; set; }
        public string idDocumento { get; set; }
        public string servicio { get; set; }
        public string nombreDocumento { get; set; }
        public string nombreArchivo { get; set; }
        public string pathURL { get; set; }
        public Nullable<int> diaCorte { get; set; }
        public Nullable<int> horaCorte { get; set; }
        public string caracterSeparador { get; set; }
        public string caracterFinLinea { get; set; }
        public int activo { get; set; }
    }
}
