//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provisiones_Fee_Tiws
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_proceso { get; set; }
        public Nullable<System.DateTime> fecha_contable { get; set; }
        public string movimiento { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> id_sociedad { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_trafico { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> importe_ingreso { get; set; }
        public Nullable<decimal> tarifa_ing { get; set; }
        public Nullable<decimal> tarifa_costo { get; set; }
        public Nullable<decimal> costo_usd { get; set; }
        public Nullable<decimal> fee_onnet { get; set; }
        public Nullable<int> margen { get; set; }
        public Nullable<decimal> fee_offnet { get; set; }
    }
}
