//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoamingDocumentoCosto
    {
        public int IdDocumentoCosto { get; set; }
        public string Anio { get; set; }
        public string FechaContable { get; set; }
        public string FechaConsumo { get; set; }
        public string Compania { get; set; }
        public string Servicio { get; set; }
        public string Grupo { get; set; }
        public string IdOperador { get; set; }
        public string NombreOperador { get; set; }
        public string Acreedor { get; set; }
        public string Material { get; set; }
        public string Trafico { get; set; }
        public string Iva { get; set; }
        public string PorcentajeIva { get; set; }
        public string Moneda { get; set; }
        public string Minutos { get; set; }
        public string Tarifa { get; set; }
        public string Monto { get; set; }
        public string MontoFacturado { get; set; }
        public string FechaFactura { get; set; }
        public string FolioDocumento { get; set; }
        public string TipoCambio { get; set; }
        public string MontoMxn { get; set; }
        public string CuentaContable { get; set; }
        public string ClaseDocumento { get; set; }
        public string ClaseDocumentoSap { get; set; }
        public string NumeroDocumentoSap { get; set; }
        public string Activo { get; set; }
        public string LineaNegocio { get; set; }
        public System.DateTime FechaCarga { get; set; }
    }
}
