//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaRoaming
    {
        public int Id { get; set; }
        public string Sentido { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Id_Operador { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> ToData { get; set; }
        public Nullable<decimal> ToSMSMo { get; set; }
        public Nullable<decimal> ToVoiceMo { get; set; }
        public Nullable<decimal> ToVoiceMt { get; set; }
        public Nullable<decimal> TfData { get; set; }
        public Nullable<decimal> TfSMSMo { get; set; }
        public Nullable<decimal> TfVoiceMo { get; set; }
        public Nullable<decimal> TfVoiceMt { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        public virtual Operador Operador { get; set; }
    }
}
