//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_Cierre
    {
        public int Id { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public System.DateTime Mes_Consumo { get; set; }
        public decimal TC_MXN { get; set; }
        public decimal TC_USD { get; set; }
        public Nullable<decimal> TC_CORPORATIVO { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
        public string Sentido { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
