//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_costos
    {
        public int Id { get; set; }
        public Nullable<decimal> Segundos { get; set; }
        public Nullable<decimal> Llamadas { get; set; }
        public Nullable<decimal> Importe_Ingreso { get; set; }
        public string Month { get; set; }
        public string Currency { get; set; }
        public string grupo { get; set; }
        public string Operador { get; set; }
        public string Servicio { get; set; }
        public string Trafico { get; set; }
        public Nullable<decimal> TarifaEXT { get; set; }
        public string Deudor { get; set; }
        public Nullable<decimal> MinFact { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string movimiento { get; set; }
        public Nullable<System.DateTime> fecha_proceso { get; set; }
        public Nullable<System.DateTime> fecha_contable { get; set; }
    }
}
